---
title: "CoronaNet Example"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE)
```

Download the script [here](https://raw.githubusercontent.com/LuMesserschmidt/stats_CoronaNet/master/Files/Course%20Scripts/R_code_CoronaNet_2.R)


***

# Set up

```{r, message=FALSE}
rm(list=ls())

library(readr)
library(tidyverse)

```

***

# Loading the dataset


```{r, eval=T,echo=F, message=F}
coronaNet <- read_csv("data/coronanet_release.csv")
wb <- read_csv("data/API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2_988619.csv", skip = 4)

businessRestrict = coronaNet %>% filter(type %in% c("Restriction and Regulation of Businesses" ,"Restriction of Non-Essential Businesses"))

wb = wb %>% gather("year", "gdpPPP", -`Country Name`, -`Country Code`, -`Indicator Name`, -`Indicator Code`, -X65)

wb = wb %>% select( -`Indicator Name`, -`Indicator Code`, -X65)
wb$year = as.numeric(wb$year)
wb$lgdpPPP= log(wb$gdpPPP)


data = merge(businessRestrict, wb %>% filter(year == 2018), by.x = 'ISO_A3', by.y = "Country Code", all.x = TRUE)

dataAgg = data %>% 
  group_by(country) %>% 
  summarise(numBusinessRestrictions = n(),
            gdpPPP = mean(gdpPPP))

dataAgg$gdpDum = ifelse(dataAgg$gdpPPP > mean(dataAgg$gdpPPP, na.rm = TRUE), "Above Average GDP", "Below Average GDP")
dataAgg = dataAgg %>% filter(!is.na(gdpDum))
```

## Explore the data (with dplyr)


```{r, eval=T,message=F}
# https://r4ds.had.co.nz/transform.html
#https://garthtarr.github.io/meatR/dplyr.html

# the dplyr counterpart to the str() function is the 'glimpse' function
glimpse(coronaNet)

# dplyr counterpart to the 'which' function is the 'filter' function
filter(coronaNet, type == "Closure and Regulation of Schools")

# Class question: what if you want to find all observations that fits the condition above but only if the initiating country (country) is Germany?

# Class question: what if you want to find all observations that fits the condition above AND the type of policy (type) is 'External Border Restrictions'?


# Class question: what if you want to find all observations that fits the condition above that are not NA for the end of policy field (date_end)



# the dplyr counterpart to the '[ ]' command to subset by rows is the slice function
slice(coronaNet, 1:10)


# the dplyr counterpart to the 'sort' function is the arrange function

arrange(coronaNet, date_start)

arrange(coronaNet, desc(date_start))


# Class question: How could you use arrange() to sort all missing values to the date_end variable? (Hint: use is.na()).



# the dplyr counterpart to the $ operator or the [,variableName] operator is 'select'

select(coronaNet, entry_type)

select(coronaNet, entry_type, country)

select(coronaNet, entry_type:country)

select(coronaNet, -c(entry_type:country))

select(coronaNet, contains('type'))



# Class question: what are some ways you can select record_id, policy_id, target_direction, ISO_A3, and ISO_A2?


# the dplyr counterpart to making a new variable is the 'mutate' function

mutate(coronaNet, newVar1 = 1, 
       newVar2 = ifelse(entry_type == 'new_entry', 1, 0)) %>%
  select(newVar1, newVar2)

# if you only want to keep the new variables, use transmute()
transmute(coronaNet, newVar1 = 1, 
          newVar2 = ifelse(entry_type == 'new_entry', 1, 0))  

```

***
# Summarizing the Data

```{r, eval=T,message=F}
coronaNet %>% group_by(country) %>%
  summarise(count = n(),
            numberOfTypesOfPolicies = n_distinct(type),
            mostActive = median(date_start))


coronaNet %>% group_by(country) %>%
  mutate(correct_type = ifelse(correct_type == 'original', 0, 1)) %>% 
  summarise(count = n(),
            numberOfTypesOfPolicies = n_distinct(type),
            mostActive = median(date_start),
            percCorrected = mean(correct_type))


coronaNet %>% group_by(country, date_start) %>%
  summarise(count = n(),
            numberOfTypesOfPolicies = n_distinct(type))

```

***
# Frequency Table

```{r, eval=T,message=F}
#install.packages("kableExtra")

library(kableExtra)

coronaNet %>% 
  filter(init_country_level == "Yes, it is at the province/state level",
         #entry_type=="new_entry",
         country=="Germany") %>%
  group_by(type) %>% 
  summarize(`Total Number of Policies`=n(),
            `Number of Countries`=length(unique(country)),
            `Number of Targeted Countries`=length(unique(target_country)),
            `% With Mandatory Enforcement`=round(mean(grepl(x=compliance,pattern="Mandatory")*100,na.rm=T),0)) %>% 
  dplyr::select(Type="type",everything()) %>% 
  filter(!is.na(Type)) %>% 
  arrange(desc(`Total Number of Policies`))  %>% 
  ungroup() %>%
  knitr::kable("html",booktabs=T,
               caption="Policies by Germany on state level (Bundesländer)") 
```



# Density Plot for Policies

In this case, we want to have the density plot for the frequencies of policies.

```{r, eval=T,message=F}
#install.packages("lubridate")

library(lubridate)

d<- coronaNet%>% 
  filter(!is.na(type)) %>% 
  group_by(type,date_announced) %>% 
  summarize(Policies=length(unique(record_id))) %>% 
  arrange(type,date_announced) %>% 
  mutate(Policies=cumsum(Policies)) %>% 
  ungroup %>% 
  mutate( type=recode(type,
      
                    `External Border Restrictions`="External\nBorder\nRestrictions",
                      `Restriction of Non-Essential Businesses`="Restriction of\nNon-Essential\nBusinesses",
                      `Restrictions of Mass Gatherings`="Restrictions of\nMass Gatherings",
                      `Restriction of Non-Essential Government Services`="Restriction of\nNon-Essential\nGovernment Services",
                      `Internal Border Restrictions`="Internal\nBorder Restrictions",
                      `External Border Restrictions`="External\nBorder Restrictions",
                      `Public Awareness Campaigns`="Public\nAwareness Campaigns",
                      `New Task Force or Bureau`="New Task Force")) %>% 
  ggplot(aes(y=Policies,x=date_announced)) +
  geom_area() +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        strip.background = element_blank()) +
  xlab("") +
  facet_wrap(~type)

d_all<-d + scale_x_date(date_labels = "%d/%m")
d_all

```



# T-Test


```{r, eval=T,message=F}

# https://www.dummies.com/education/science/biology/how-to-use-student-t-tests-to-compare-averages/

# Doing a t-test in R
# https://uc-r.github.io/t_test

# Doing a t-test by hand
# http://onlinestatbook.com/2/tests_of_means/difference_means.html
# https://stattrek.com/hypothesis-test/difference-in-means.aspx

# Interpreting p-values
# https://blog.minitab.com/blog/adventures-in-statistics-2/how-to-correctly-interpret-p-values


# class question: what is the average gdpPPP


# lets see if there is a statistical difference in the number of business restrictions for countries over the average GDP PPP level 
# compared to countries under the average GDP PPP level
t.test(dataAgg %>% filter(gdpPPP > mean(dataAgg$gdpPPP, na.rm = TRUE)) %>% select(numBusinessRestrictions),
       dataAgg %>% filter(gdpPPP <= mean(dataAgg$gdpPPP, na.rm = TRUE))%>% select(numBusinessRestrictions))


dataAgg %>% filter(gdpPPP > mean(dataAgg$gdpPPP, na.rm = TRUE)) %>% summarise(avgNumBusinessRestrictions = mean(numBusinessRestrictions, na.rm = TRUE))  
dataAgg %>% filter(gdpPPP <= mean(dataAgg$gdpPPP, na.rm = TRUE)) %>% summarise(avgNumBusinessRestrictions = mean(numBusinessRestrictions, na.rm = TRUE))  

```



